require_relative './models/questions_database.rb'
require_relative './models/db_object.rb'
require_relative './models/user.rb'
require_relative './models/question.rb'
require_relative './models/question_follow.rb'
require_relative './models/question_like.rb'
require_relative './models/reply.rb'
require_relative './models/tag.rb'
